server:
  port: 9090

spring:
  application:
    name: sharding-jdbc-demo

mybatis:
  type-aliases-package: com.example.shardingjdbcdemo.entity
  mapper-locations: classpath:mapper/*.xml

#数据源
sharding:
  jdbc:
    datasource:
      names: ds0,ds1,ds2,ds3
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user_0?useSSL=false&characterEncoding=utf8
        username: root
        password: admin
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user_1?useSSL=false&characterEncoding=utf8
        username: root
        password: admin
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user_2?useSSL=false&characterEncoding=utf8
        username: root
        password: admin
      ds3:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user_3?useSSL=false&characterEncoding=utf8
        username: root
        password: admin

    config:
      sharding:
        props:
          sql.show: true
        tables:
          order_info_:
            actual-data-nodes: ds${0..3}.order_info_${0..9}  #数据节点
            table-strategy:  #分表策略
              inline:
                sharding-column: order_id
                algorithm-expression: order_info_${order_id % 10}
            keyGenerator:
              type: SNOWFLAKE
              column: order_id
          address_info_:
            actual-data-nodes: ds${0..3}.order_info_${0..9}  #数据节点
            table-strategy:  #分表策略
              inline:
                sharding-column: address_id
                algorithm-expression: address_info_${address_id % 2}
            keyGenerator:
              type: SNOWFLAKE
              column: address_id
        #绑定表,有利于join
        binding-tables:
          - order_info_ address_info_

        defaultDataSourceName: ds0
        defaultDatabaseStrategy:
          inline:
            shardingColumn: user_id
            algorithmExpression: ds${user_id % 4}
