server:
  port: 9090

spring:
  application:
    name: sharding-jdbc-demo

mybatis:
  type-aliases-package: com.example.shardingjdbcdemo.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
